# File: alicloud_sets.yaml

static_vms:
  - &us_west_vm1
    user_name: root
    ssh_private_key: /Users/cangya/workspace/perfkit_keyfile/iperf/perfkitbenchmarker_keyfile
    ip_address: 47.88.18.104
    os_type: debian


ping: &ping_us
  flags:
    ping_use_external_ip: True
  vm_groups:
    vm_1:
      static_vms:
        - *us_west_vm1

aerospike: &aerospike_us
  vm_groups:
    default:
      static_vms:
        - *us_west_vm1


benchmarks:
#  - iperf: *iperf
#  - netperf: *netperf
#  - mesh_network: *mesh_network
#  - ping: *ping
   - aerospike: *aerospike_us
