# File: network_config.yaml
# Regions:
#    us-west-1
static_vms:
  - &ap_southeast_vm1
    user_name: root
    ssh_private_key: /root/.ssh/perfkitbenchmarker_keyfile
    ip_address: 47.88.136.71
    os_type: debian
  - &cn_shenzhen_vm1
    user_name: root
    ssh_private_key: /root/.ssh/perfkitbenchmarker_keyfile
    ip_address: 120.24.2.131
    os_type: debian

iperf: &muti_iperf
  vm_groups:
    vm_1:
      static_vms:
        - *ec2_us_west_vm1
    vm_2:
      static_vms:
        - *ec2_us_west_vm1


# If you choose to, you can specify which benchmarks should be
# run in your config file. This will even let you run the same
# benchmark multiple times with different configs.
benchmarks:
  - iperf: *muti_iperf



