# File: network_config.yaml
# Regions:
#    cn-hangzhou
#    us-west-1
# mkdir .ssh;echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDuq/k7M0pcdRG4xtnwLzJkuBFmdzMNOqk83BbnAA7jZnTUIDwaMyvbn9qQTvROpsP5vo4xalnG+f6LgmpB5f5JC60Zk4tWLyiF1R/9eHlt3ipXTw01Fj2xlpGHYjRehRZlK4Gog27f1uDZRdyqajzfcUkN2P56dLyG4J6dLdrxuH7SX3vkQ0/C5kVWCvjIMDWhN8YA07kfMHUnTmY5UsjySkapechirmDfnWF4heEvVv8ir55iLAT+Evpb2QcVh7wg2De0zFsAtylzjbDoVhQQDTZMKqTzM8VR13Em6AHEZNXpHXwOsqwot4pAiV4e6yL0JyQocyDD7IARVBNHEXL9 cangya@gaolonggldeMacBook-Air.local" > .ssh/authorized_keys
# /root/.ssh/perfkitbenchmarker_keyfile

# us-west / ap-southeast-1 use static vms
static_vms:
  - &cn_hangzhou_vm1
    user_name: root
    ssh_private_key: /root/.ssh/perfkitbenchmarker_keyfile
    ip_address: 121.43.189.53
    internal_ip: 192.168.1.13
    os_type: debian
  - &us_west_vm1
    user_name: root
    ssh_private_key: /root/.ssh/perfkitbenchmarker_keyfile
    ip_address: 47.88.60.207
    internal_ip: 10.0.0.2
    os_type: debian


ping: &ping_muti
  flags:
    ping_use_external_ip: False
  vm_groups:
    vm_1:
      static_vms:
        - *cn_hangzhou_vm1
    vm_2:
      static_vms:
        - *us_west_vm1


# If you choose to, you can specify which benchmarks should be
# run in your config file. This will even let you run the same
# benchmark multiple times with different configs.
benchmarks:
#  - iperf: *iperf_singapore_hangzhou
#  - netperf: *netperf_hangzhou_singapore
#  - iperf: *iperf_two_core_aws

#  - mesh_network: *mesh_network_ali
#  - mesh_network: *mesh_network_aws

  - ping: *ping_muti


