# Declare any anchors you may want to use later.
# Some vm_spec sample:

static_vms:
  - &us_west_vm1
    user_name: root
    ssh_private_key: /Users/cangya/workspace/perfkit_keyfile/iperf/perfkitbenchmarker_keyfile
    ip_address: 47.88.18.104
    os_type: debian

two_core_4GB: &two_core_4GB
  AliCloud:
    zone: us-west-1b
    machine_type: ecs.s2.large
  AWS:
    zone: us-west-1b
    machine_type: t2.medium

four_core_8GB: &four_core_8GB
  AliCloud:
    zone: us-west-1b
    machine_type: ecs.s3.large
  AWS:
    zone: us-west-1b
    machine_type: c4.xlarge

# Some disk_spec sample:
remote_ssd: &remote_ssd_500gb
  AliCloud:
    disk_size: 500
    mount_point: /scratch
    disk_type: remote_ssd
  AWS:
    disk_size: 500
    mount_point: /scratch
    disk_type: remote_ssd

# Multi cloud iperf config.
iperf: &iperf_two_core_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    vm_1:
      cloud: AliCloud
      vm_spec: *two_core_4GB
    vm_2:
      cloud: AliCloud
      vm_spec: *two_core_4GB

# Multi cloud iperf config.
iperf: &iperf_two_core_aws
  vm_groups:
    vm_1:
      cloud: AWS
      vm_spec: *two_core_4GB
    vm_2:
      cloud: AWS
      vm_spec: *two_core_4GB

# Multi cloud fio config.
fio: &fio_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud fio config.
fio: &fio_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud ping config.
ping: &ping_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB
      vm_count: 2

# Multi cloud ping config.
ping: &ping_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB
      vm_count: 2

# Multi cloud sysbench_oltp config.
sysbench_oltp: &sysbench_oltp_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud sysbench_oltp config.
sysbench_oltp: &sysbench_oltp_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud copy_throughput config.
copy_throughput: &copy_throughput_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb


# Multi cloud copy_throughput config.
copy_throughput: &copy_throughput_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud bonnie config.
bonnie++: &bonnie_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud bonnie config.
bonnie++: &bonnie_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB
      disk_spec: *remote_ssd_500gb

# Multi cloud mesh_network config.
mesh_network: &mesh_network_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB

# Multi cloud mesh_network config.
mesh_network: &mesh_network_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB

# Multi cloud redis config.
redis_ali_aws: &redis_ali
  flags:
    ali_io_optimized: optimized
    ali_system_disk_type: cloud_ssd
    ali_use_vpc: True
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB

# Multi cloud redis config.
redis_ali_aws: &redis_aws
  vm_groups:
    default:
      cloud: AWS
      vm_spec: *two_core_4GB

# Multi cloud redis config.
coremark_ali: &coremark_ali
  vm_groups:
    default:
      cloud: AliCloud
      vm_spec: *two_core_4GB

# If you choose to, you can specify which benchmarks should be
# run in your config file. This will even let you run the same
# benchmark multiple times with different configs.
benchmarks:
#  - iperf: *iperf_two_core_ali
#  - iperf: *iperf_two_core_aws
#  - fio: *fio_ali
#  - fio: *fio_aws
#  - ping: *ping_ali
#  - ping: *ping_aws
##  - ping: *ping_ali_cross_zone
#  - sysbench_oltp: *sysbench_oltp_ali
#  - sysbench_oltp: *sysbench_oltp_aws
#  - copy_throughput: *copy_throughput_ali
#  - copy_throughput: *copy_throughput_aws
#  - bonnie++: *bonnie_ali
#  - bonnie++: *bonnie_aws
#  - mesh_network: *mesh_network_ali
#  - mesh_network: *mesh_network_aws
#  - redis: *redis_ali
#  - redis: *redis_aws
  - coremark: *coremark_ali

